### ISSUE TITLE
Update Mac executable

### ISSUE THREAD

**Issue by nalmadi** [nalmadi/fix8#184]

**Comment by AgLyx3** [comment]
**1. Change all relative import to absolute import**
e.g. 
old—-----------------
```python
from .merge_fixations_dialog import MergeFixationsDialog
```
new—-----------------
```python
from merge_fixations_dialog import MergeFixationsDialog
```

**2. Import sys and os.path & Add a method resourcePath(self, relativePath)  in fix8.Fix8**
```python
import sys
import os.path

def resourcePath(self, relativePath):
       try:
           # PyInstaller creates a temp folder and stores path in _MEIPASS
           basePath = sys._MEIPASS
       except Exception:
           basePath = os.path.abspath(".")


       return os.path.join(basePath, relativePath)
```

[_reference:_](https://stackoverflow.com/questions/65972784/why-am-i-getting-pyinstaller-filenotfounderror-errno-2-no-such-file-or-direct)

Notes： I didn’t directly use resourcePath because I put resourcePath in the Fix8 class. There might be a more reasonable place to put this method and then we could remove ‘self’ as the argument.

**3. Import Fix8 class into canvas_resources.py & ui_main_window.py**
```python
from fix8 import Fix8
```

**4. Changes all “src/…” to resourcePath(Fix8, “…”)** 
(1 change in fix8.py, 4 changes in ui_main_window.py, and 1 change in canvas_resources.py in total)
E.g.
Old —---------------------------------------------------
```python
self.setWindowIcon(QIcon("src/.images/icon.ico"))
```
New —---------------------------------------------------
```python
self.setWindowIcon(QIcon(Fix8.resourcePath(Fix8, ".images/icon.ico")))
```
**5. Download Pyinstaller and then Run Pyinstaller on fix8.py**
“pip install pyinstaller”
“pyinstaller --onefile --icon=.images/Fix8_icon.ico fix8.py”
Issue: icon doesn’t work properly

If not working, try to paste the document on the next page into the spec file and then run “pyinstaller fix8.spec”

```
# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files
datas = []
datas += collect_data_files('.images')
a = Analysis(
    ['fix8.py'],
    pathex=[],
    binaries=[],
    datas=[('my_theme.xml','.'), ('.images','.images')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='fix8',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
```
